name: listview_screenshot
repository: https://github.com/AoEiuV020/listview_screenshot

packages:
  - apps/**
  - packages/**

scripts:
  worker2js:
    steps:
      - melos worker2jsImageMerge
  worker2jsImageMerge:
    exec: cd web && dart compile js imageMergeTransform.dart -o imageMergeTransform.js -O4
    packageFilters:
      scope: 'example'

  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  doc:
    exec: dart doc .
    packageFilters:
      ignore: '*example*'
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  test:
    run: flutter test --no-pub --coverage
    exec:
      concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: test