name: listview_screenshot
description: "Supports long screenshots, suitable for ListView and other scrollable widgets,"
version: 3.2.0
repository: https://github.com/AoEiuV020/listview_screenshot/tree/main/packages/listview_screenshot
issue_tracker: https://github.com/AoEiuV020/listview_screenshot/issues

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7
  isolate_transformer: ^1.1.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.0.0
