# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag-pattern on pub.dev: 'v{{version}}'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    name: publish packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: 'Installs the Dart SDK and sets up the pipeline for usage with pub.dev (this sets up OIDC)'
        uses: dart-lang/setup-dart@v1
      - run: |
          ./script/prepare.sh
          ./script/publish.sh